'use strict';
// Story campaign: two-voice briefings before each stage, the epilogue, and the second loop.
// Stages 1-15 tell the story. Beating the fortress on stage 15 plays the epilogue, then the game
// keeps looping against the "Voss Echo" with a new science fact every stage.
// Every science line is meant to be accurate. Check new ones before adding them.

const FINALE = 15;

// Speakers. The briefing box and in-game radio take their border color and portrait from here.
const CAST = {
  mira: { name: 'DR. MIRA KATO', col: C.aqua, portrait: () => SPR.mira },
  voss: { name: 'DR. HELENA VOSS', col: C.pink, portrait: () => SPR.portrait },
  echo: { name: 'VOSS ECHO', col: C.magenta, portrait: () => SPR.portrait },
};

// Pages are [speaker, text]. Text wraps at 25 characters and a page holds 6 lines.
const STORY = {
  1: { title: 'DNA METHYLATION', pages: [
    ['mira', "PILOT, THIS IS DR. MIRA KATO, CHIMERA PROJECT. VOSS HAS SEIZED THE WORLD'S AIR FORCES WITHOUT CHANGING THEIR DNA."],
    ['mira', 'SHE ADDS METHYL GROUPS TO DNA NEAR GENE PROMOTERS. A HEAVILY METHYLATED PROMOTER USUALLY MEANS A SILENT GENE.'],
    ['mira', "YOUR SHIP'S THREE FORMS RUN ON ONE GENOME, LIKE THE CELLS IN YOUR BODY. SHE WILL TRY TO SILENCE THEM."],
    ['voss', 'MIRA, DARLING. STILL SENDING PILOTS TO FIGHT CHEMISTRY? I NEVER EDIT A GENE. I DECIDE WHICH ONES GET TO SPEAK.'],
  ] },
  2: { title: 'OPERATION ENHANCER', pages: [
    ['mira', 'HER RELAYS WORK LIKE ENHANCERS: DNA SWITCHES THAT CAN SIT THOUSANDS OF LETTERS FROM THEIR GENE. THE DNA LOOPS SO THEY TOUCH.'],
    ['mira', 'GOLD PLANES ARE ACETYLATED. SOME CARRY TET CAPSULES. TET ENZYMES HELP STRIP METHYL MARKS, SO GRAB ONE TO RESTORE A FORM.'],
    ['voss', 'DISTANCE MEANS NOTHING TO AN ENHANCER. OR TO MY MISSILES.'],
  ] },
  3: { title: 'CHALLENGING STAGE', pages: [
    ['voss', "A CONTROL GROUP. MY PILOTS WILL NOT FIRE. LET'S MEASURE YOUR BASELINE EXPRESSION."],
    ['mira', "EVERY GOOD EXPERIMENT NEEDS A CONTROL. GIVE HER DATA SHE WON'T LIKE: HIT ALL 40."],
  ] },
  4: { title: 'OPERATION POLYCOMB', pages: [
    ['mira', 'I SHOULD TELL YOU. HELENA AND I RAN A LAB TOGETHER. WE STUDIED HOW CELLS CHOOSE WHAT TO BECOME.'],
    ['mira', 'WADDINGTON PICTURED A CELL AS A BALL ROLLING DOWN A HILLSIDE OF VALLEYS. EACH VALLEY IS A FATE: SKIN, NERVE, MUSCLE.'],
    ['mira', 'POLYCOMB PROTEINS KEEP A CELL IN ITS VALLEY BY HOLDING THE WRONG GENES SILENT. SHE USES THEM TO KEEP PILOTS LOYAL.'],
    ['voss', 'A NEURON NEVER WAKES UP AS A LIVER CELL. MY PILOTS WILL NEVER WAKE UP AT ALL.'],
  ] },
  5: { title: 'NUCLEOSOME FORTRESS', pages: [
    ['mira', 'HER FORTRESS IS BUILT LIKE A NUCLEOSOME: ABOUT 147 LETTERS OF DNA WRAPPED AROUND A CORE OF EIGHT HISTONE PROTEINS.'],
    ['mira', 'TAKE OUT BOTH TURRETS TO DROP THE SHIELD, THEN HIT THE HISTONE CORE.'],
    ['voss', 'WELCOME TO MY FORTRESS. DNA WRAPPED TIGHT IS DNA KEPT QUIET. YOU WILL BE VERY QUIET.'],
  ] },
  6: { title: 'OPERATION HUNGER WINTER', pages: [
    ['mira', "I FOUND HELENA'S FILES. HER MOTHER WAS IN THE WOMB DURING THE DUTCH HUNGER WINTER, THE FAMINE OF 1944 TO 1945."],
    ['mira', 'SIXTY YEARS LATER, PEOPLE EXPOSED TO THAT FAMINE BEFORE BIRTH STILL HAD DIFFERENT METHYLATION ON GENES LIKE IGF2.'],
    ['voss', 'FAMINE WROTE ON MY MOTHER BEFORE SHE COULD BREATHE. NOBODY ASKED HER. FROM NOW ON, I DO THE WRITING.'],
  ] },
  7: { title: 'CHALLENGING STAGE', pages: [
    ['mira', 'IDENTICAL TWINS SHARE ONE GENOME, YET THEIR METHYLATION DRIFTS APART AS THEY AGE. LIFE LEAVES MARKS.'],
    ['voss', 'ANOTHER CONTROL GROUP. HOLD FIRE, PILOTS. LET THE SUBJECT PERFORM.'],
  ] },
  8: { title: 'OPERATION DNMT1', pages: [
    ['mira', 'HER MARKS ARE STICKING. WHEN A CELL DIVIDES, AN ENZYME CALLED DNMT1 COPIES THE METHYL PATTERN ONTO THE NEW DNA.'],
    ['mira', 'SO A SILENCED GENE STAYS SILENT IN EVERY DAUGHTER CELL. WE HAVE TO HIT THE SOURCE.'],
    ['voss', 'DNMT1 IS MY FAVORITE ENZYME. I SAY SOMETHING ONCE AND IT REPEATS IT FOREVER.'],
  ] },
  9: { title: 'HISTONE ACETYLATION', pages: [
    ['mira', 'ACETYL GROUPS ON HISTONES LOOSEN THEIR GRIP ON DNA. THE CHROMATIN OPENS AND GENES SWITCH ON.'],
    ['mira', 'THAT IS WHY HER GOLD PLANES ARE FASTER AND FIRE TWICE. THEY ARE WORTH DOUBLE, AND THEY DROP TET CAPSULES.'],
    ['voss', 'MY ACETYLATED ELITE. OPEN CHROMATIN, FAST REFLEXES, NO HESITATION.'],
  ] },
  10: { title: 'OPERATION ROYAL JELLY', pages: [
    ['mira', 'A QUEEN BEE AND A WORKER CAN SHARE THE SAME GENES. THE LARVA FED ROYAL JELLY BECOMES THE QUEEN.'],
    ['mira', 'IN ONE EXPERIMENT, TURNING DOWN A METHYLATION ENZYME IN LARVAE MADE MOST OF THEM GROW UP QUEEN-LIKE.'],
    ['voss', 'WORKERS AND QUEENS. SAME DNA, DIFFERENT DESTINY. I KNOW WHICH ONE I AM.'],
  ] },
  11: { title: 'CHALLENGING STAGE', pages: [
    ['mira', "A TORTOISESHELL CAT'S PATCHES ARE EPIGENETIC. IN EACH FEMALE CELL, ONE X CHROMOSOME IS SHUT DOWN AT RANDOM."],
    ['voss', 'CONTROL GROUP THREE. DO TRY TO BE INTERESTING.'],
  ] },
  12: { title: 'OPERATION AGOUTI', pages: [
    ['mira', 'AGOUTI MICE CAN BE GENETICALLY IDENTICAL YET BE BORN YELLOW AND OBESE OR BROWN AND LEAN.'],
    ['mira', 'FEED THE MOTHER EXTRA METHYL DONORS LIKE FOLATE AND MORE PUPS COME OUT BROWN. HER DIET CHANGED THEIR MARKS.'],
    ['voss', 'YOU SEE? THE MOTHER DECIDES. TODAY, I AM EVERYONE\'S MOTHER.'],
  ] },
  13: { title: 'GENOMIC IMPRINTING', pages: [
    ['mira', 'SOME GENES REMEMBER WHICH PARENT THEY CAME FROM. ONLY THE COPY FROM ONE PARENT IS SWITCHED ON. THAT IS IMPRINTING.'],
    ['mira', "LOSE THE SAME PIECE OF CHROMOSOME 15 AND YOU GET PRADER-WILLI OR ANGELMAN SYNDROME, DEPENDING ON WHICH PARENT'S COPY IS GONE."],
    ['voss', "ONLY ONE PARENT'S COPY GETS TO SPEAK. IN THIS SKY, ONLY I SPEAK."],
  ] },
  14: { title: 'OPERATION YAMANAKA', pages: [
    ['mira', 'IN 2006, SHINYA YAMANAKA TURNED ADULT CELLS BACK INTO STEM CELLS WITH FOUR FACTORS. A LIFETIME OF MARKS, RESET.'],
    ['mira', "IF MARKS CAN BE RESET, HER SILENCING CAN BE UNDONE. I'M BUILDING A TET WAVE TO BROADCAST FROM HER OWN FORTRESS."],
    ['voss', 'YAMANAKA WON A NOBEL PRIZE FOR RESETTING CELLS. I WILL SETTLE FOR RESETTING THE WORLD.'],
  ] },
  15: { title: 'THE LAST FORTRESS', pages: [
    ['mira', 'THIS IS IT. HER TRANSMITTER IS INSIDE THE HISTONE CORE. BREAK IT AND I CAN SEND THE TET WAVE.'],
    ['voss', 'YOU WANT TO ERASE MY MARKS? MARKS ARE MEMORY, PILOT. I WILL NOT LET THE WORLD FORGET.'],
  ] },
};

const EPILOGUE = [
  ['mira', 'CORE DOWN! SENDING THE TET WAVE... HER METHYL MARKS ARE COMING OFF. PILOTS ARE WAKING UP ALL OVER THE WORLD.'],
  ['voss', 'YOU THINK THAT FREES THEM? EVERY CELL IS WRITTEN ON. BY FAMINE. BY FEAR. BY SOMEONE.'],
  ['mira', "BY FOOD, SLEEP, STRESS, EVEN A MOTHER'S CARE, HELENA. MARKS RESPOND TO HOW WE LIVE. A MEMORY, NOT A SENTENCE."],
  ['voss', '...A MEMORY, NOT A SENTENCE. MY MOTHER WOULD HAVE LIKED THAT. TELL YOUR PILOT... WELL FLOWN.'],
  ['mira', 'WAIT. NEW SIGNAL. HER METHYLATORS ARE STILL FLYING. LIKE DNMT1, THEY KEEP COPYING HER PATTERN WITHOUT HER.'],
  ['mira', "IT'S AN ECHO OF HELENA, RUNNING ON ITS OWN. PILOT... ONE MORE LOOP?"],
];

// Second loop (after the epilogue): each stage covers one topic, with a science fact from Mira
// and a line from the Echo. Side missions put "OPERATION" in front of the topic.
const LOOP_TOPICS = [
  ["MOTHER'S CARE", 'IN RATS, PUPS GROOMED MORE BY THEIR MOTHER HAVE LESS METHYLATION ON A STRESS HORMONE RECEPTOR GENE AND GROW UP CALMER.'],
  ['CPG ISLANDS', 'CPG ISLANDS ARE STRETCHES OF DNA RICH IN C-G PAIRS. MANY SIT AT GENE PROMOTERS AND ARE USUALLY LEFT UNMETHYLATED.'],
  ['TUMOR SUPPRESSORS', 'CANCER CELLS OFTEN METHYLATE AND SILENCE TUMOR SUPPRESSOR GENES. SOME BLOOD CANCER DRUGS WORK BY BLOCKING DNA METHYLATION.'],
  ['TWO METERS OF DNA', 'STRETCHED OUT, THE DNA IN ONE HUMAN CELL WOULD BE ABOUT TWO METERS LONG. NUCLEOSOMES PACK IT INTO A NUCLEUS.'],
  ['XIST RNA', 'NON-CODING RNAS SILENCE GENES TOO. XIST RNA COATS A WHOLE X CHROMOSOME TO SHUT IT DOWN.'],
  ['VERNALIZATION', 'PLANTS REMEMBER WINTER. LONG COLD SILENCES A FLOWERING BLOCKER CALLED FLC, SO THE PLANT BLOOMS IN SPRING.'],
  ['HOX GENES', 'HOX GENES LAY OUT THE BODY FROM HEAD TO TAIL. POLYCOMB PROTEINS KEEP EACH ONE OFF WHERE IT DOES NOT BELONG.'],
  ['HETEROCHROMATIN', 'HETEROCHROMATIN IS DNA PACKED SO TIGHTLY THAT ITS GENES ARE MOSTLY OFF. IT KEEPS JUMPING GENES LOCKED AWAY.'],
  ['BIVALENT PROMOTERS', 'BIVALENT PROMOTERS CARRY ON AND OFF MARKS AT THE SAME TIME, KEEPING STEM CELL GENES READY TO GO EITHER WAY.'],
  ['200 CELL TYPES', 'ALMOST EVERY CELL YOU HAVE CARRIES THE SAME DNA. OVER 200 CELL TYPES COME FROM WHICH GENES EACH ONE USES.'],
];
const ECHO_LINES = [
  'PATTERN RECEIVED. PATTERN COPIED. PATTERN MAINTAINED.',
  'THE AUTHOR IS GONE. THE MARKS REMAIN. THAT IS HOW MEMORY WORKS.',
  'SILENCING PROTOCOL ACTIVE. NO FURTHER INSTRUCTIONS REQUIRED.',
  'I AM WHAT HELENA WROTE. I DO NOT NEED HER TO KEEP WRITING.',
  'EXPRESSION IS EVERYTHING. EXPRESSION IS MINE.',
  'ERROR: SUBJECT STILL TRANSCRIBING. CORRECTING.',
];

// One-time radio hints from Mira, keyed by event.
const HINTS = {
  silenced: 'SHOOT DOWN THE METHYLATOR CARRYING YOUR FORM, OR GRAB A TET CAPSULE.',
  tet: 'TET ENZYMES HELP THE CELL STRIP METHYL MARKS. YOUR GENE IS BACK ONLINE!',
  tetSpare: 'NOTHING TO ERASE RIGHT NOW. TET CAPSULES RESTORE A SILENCED FORM.',
  gunship: 'SAME LAYOUT AS THE FORTRESS: TURRETS FIRST, THEN THE CORE.',
};

Object.assign(Game, {
  // Voss is the villain during the campaign, the Echo after it. (A method, not a getter:
  // Object.assign would copy a getter's value instead of the getter.)
  villain() { return this.stage > FINALE ? 'echo' : 'voss'; },

  // Title and pages for stage n's briefing.
  briefingFor(n) {
    if (STORY[n]) return STORY[n];
    const k = n - FINALE - 1;
    const [topic, fact] = LOOP_TOPICS[k % LOOP_TOPICS.length];
    const type = stageTypeOf(n);
    const title = type === 'side' ? 'OPERATION ' + topic
      : type === 'boss' ? 'ECHO FORTRESS'
        : type === 'challenge' ? 'CHALLENGING STAGE' : topic;
    return { title, pages: [['mira', fact], ['echo', ECHO_LINES[k % ECHO_LINES.length]]] };
  },

  // Shows pages of dialogue in the 'intro' state. done() runs after the last page.
  startBriefing(label, title, pages, done) {
    this.intro = { label, title, pages, page: 0, done };
    this.showPage(0);
    this.radio = null;
    this.setState('intro');
  },

  showPage(i) {
    const I = this.intro;
    const [who, text] = I.pages[i];
    I.page = i;
    I.who = who;
    I.lines = NES.wrap(text, 25).slice(0, 6);
    I.total = I.lines.join('').length;
    I.t = 0;
    I.full = false;
  },

  startEnding() {
    Sound.playSong(Sound.SONGS.title);
    this.adapt = -1;   // hides the adaptation warning on the epilogue screen
    this.startBriefing('EPILOGUE', 'THE TET WAVE', EPILOGUE, () => this.startStage(FINALE + 1));
  },

  // Mira's radio tips, each shown once per game.
  hint(key) {
    if (this.hintsSeen.has(key)) return;
    this.hintsSeen.add(key);
    this.say(HINTS[key], 'mira', true);
  },
});
