'use strict';
// Story campaign: two-voice briefings before each planet mission, story beats that follow your
// progress, galaxy arrivals, the epilogue, and the Echo campaign (New Game+).
// A story planet's STRONGHOLD briefing (PLANET_STORY) says why we fight there and what the boss is.
// Every other mission gets a field briefing: Mira sets up the mission, adds a science note from
// FIELD_NOTES, and Voss answers. Voss's personal story is told in STORY_BEATS, keyed to how many
// systems you have secured, so it stays in order on any route.
// Every science line is meant to be accurate. Check new ones before adding them.

// Speakers. The briefing box and in-game radio take their border color and portrait from here.
const CAST = {
  mira: { name: 'DR. MIRA KATO', col: C.aqua, portrait: () => SPR.mira },
  voss: { name: 'DR. HELENA VOSS', col: C.pink, portrait: () => SPR.portrait },
  echo: { name: 'VOSS ECHO', col: C.magenta, portrait: () => SPR.portrait },
};

// Pages are [speaker, text]. Text wraps at 25 characters and a page holds 6 lines.
const PLANET_STORY = {
  // ---- SOL ----
  earth: { title: 'DNA METHYLATION', pages: [
    ['mira', "PILOT, THIS IS DR. MIRA KATO, CHIMERA PROJECT. VOSS HAS SEIZED THE WORLD'S AIR FORCES WITHOUT CHANGING THEIR DNA."],
    ['mira', 'SHE ADDS METHYL GROUPS TO DNA NEAR GENE PROMOTERS. A HEAVILY METHYLATED PROMOTER USUALLY MEANS A SILENT GENE.'],
    ['mira', "YOUR SHIP'S THREE FORMS RUN ON ONE GENOME, LIKE THE CELLS IN YOUR BODY. SHE WILL TRY TO SILENCE THEM."],
    ['mira', 'HER HISTONE BUNKER HOLDS EARTH. BREAK THROUGH HER SCREEN, THEN DESTROY EVERY GUN ON THE BUNKER.'],
    ['voss', 'MIRA, DARLING. STILL SENDING PILOTS TO FIGHT CHEMISTRY? I NEVER EDIT A GENE. I DECIDE WHICH ONES GET TO SPEAK.'],
  ] },
  mars: { title: 'OPERATION ENHANCER', pages: [
    ['mira', 'HER RELAY ON MARS WORKS LIKE AN ENHANCER: A DNA SWITCH THAT CAN SIT THOUSANDS OF LETTERS FROM ITS GENE. THE DNA LOOPS SO THEY TOUCH.'],
    ['mira', 'GOLD PLANES ARE ACETYLATED. SOME CARRY TET CAPSULES. TET ENZYMES HELP STRIP METHYL MARKS, SO GRAB ONE TO RESTORE A FORM.'],
    ['mira', 'HER DREADNOUGHT GUARDS THE RELAY. FLY THE LENGTH OF IT AND DESTROY EVERY TURRET, HANGAR AND CORE.'],
    ['voss', 'DISTANCE MEANS NOTHING TO AN ENHANCER. OR TO MY MISSILES.'],
  ] },
  venus: { title: 'OPERATION POLYCOMB', pages: [
    ['mira', 'I SHOULD TELL YOU. HELENA AND I RAN A LAB TOGETHER. WE STUDIED HOW CELLS CHOOSE WHAT TO BECOME.'],
    ['mira', 'WADDINGTON PICTURED A CELL AS A BALL ROLLING DOWN A HILLSIDE OF VALLEYS. EACH VALLEY IS A FATE: SKIN, NERVE, MUSCLE.'],
    ['mira', 'POLYCOMB PROTEINS KEEP A CELL IN ITS VALLEY BY HOLDING THE WRONG GENES SILENT. SHE USES THEM TO KEEP PILOTS LOYAL.'],
    ['mira', 'HER BUNKER HOLDS VENUS. ITS PILOTS ARE LOYAL TO THE LAST. BREAK THROUGH AND TAKE IT.'],
    ['voss', 'A NEURON NEVER WAKES UP AS A LIVER CELL. MY PILOTS WILL NEVER WAKE UP AT ALL.'],
  ] },
  // ---- ALPHA CENTAURI ----
  proxima: { title: 'OPERATION DNMT1', pages: [
    ['mira', 'HER MARKS ARE STICKING. WHEN A CELL DIVIDES, AN ENZYME CALLED DNMT1 COPIES THE METHYL PATTERN ONTO THE NEW DNA.'],
    ['mira', 'SO A SILENCED GENE STAYS SILENT IN EVERY DAUGHTER CELL. HER REPLICATOR SHIP COPIES HER FLEET THE SAME WAY.'],
    ['mira', 'FLY OVER IT AND KNOCK OUT EVERY TARGET. SPLITTER PLANES BREAK IN TWO WHEN SHOT.'],
    ['voss', 'DNMT1 IS MY FAVORITE ENZYME. I SAY SOMETHING ONCE AND IT REPEATS IT FOREVER.'],
  ] },
  toliman: { title: 'TWIN DRIFT', pages: [
    ['mira', 'IDENTICAL TWINS SHARE ONE GENOME, YET THEIR METHYLATION DRIFTS APART AS THEY AGE. LIFE LEAVES MARKS.'],
    ['mira', 'TOLIMAN AND RIGIL KENTAURUS ARE TWIN STARS. HER DNMT1 COPIER KEEPS BOTH FLEETS MARKED THE SAME.'],
    ['mira', 'THE COPIER REBUILDS ONE LOST TURRET, SO KEEP HITTING IT.'],
    ['voss', 'TWINS DRIFT APART. MY FLEETS NEVER WILL.'],
  ] },
  // ---- BARNARD'S STAR ----
  hive: { title: 'HISTONE ACETYLATION', pages: [
    ['mira', 'ACETYL GROUPS ON HISTONES LOOSEN THEIR GRIP ON DNA. THE CHROMATIN OPENS AND GENES SWITCH ON.'],
    ['mira', 'THAT IS WHY HER GOLD PLANES ARE FASTER AND FIRE TWICE. THEY ARE WORTH DOUBLE, AND THEY DROP TET CAPSULES.'],
    ['mira', 'HER HIVE NEST BREEDS DRONES ON BARNARD B. ITS CORE SHIELDS UP WHILE A SWARM LAUNCHES, SO STRIKE BETWEEN SWARMS.'],
    ['voss', 'MY ACETYLATED ELITE. OPEN CHROMATIN, FAST REFLEXES, NO HESITATION.'],
  ] },
  nectar: { title: 'OPERATION ROYAL JELLY', pages: [
    ['mira', 'A QUEEN BEE AND A WORKER CAN SHARE THE SAME GENES. THE LARVA FED ROYAL JELLY BECOMES THE QUEEN.'],
    ['mira', 'IN ONE EXPERIMENT, TURNING DOWN A METHYLATION ENZYME IN LARVAE MADE MOST OF THEM GROW UP QUEEN-LIKE.'],
    ['mira', 'NECTAR IS WHERE SHE RAISES NEW QUEENS. HER HIVE ARK GUARDS IT, FULL OF DRONE HANGARS. BRING IT DOWN.'],
    ['voss', 'WORKERS AND QUEENS. SAME DNA, DIFFERENT DESTINY. I KNOW WHICH ONE I AM.'],
  ] },
  // ---- SIRIUS ----
  agouti: { title: 'OPERATION AGOUTI', pages: [
    ['mira', 'AGOUTI MICE CAN BE GENETICALLY IDENTICAL YET BE BORN YELLOW AND OBESE OR BROWN AND LEAN.'],
    ['mira', 'FEED THE MOTHER EXTRA METHYL DONORS LIKE FOLATE AND MORE PUPS COME OUT BROWN. HER DIET CHANGED THEIR MARKS.'],
    ['mira', 'HER BATTLESHIP HERE IS CALLED THE BARR BODY: THE NAME FOR AN X CHROMOSOME THAT HAS BEEN SHUT DOWN AND PACKED TIGHT.'],
    ['voss', "YOU SEE? THE MOTHER DECIDES. TODAY, I AM EVERYONE'S MOTHER."],
  ] },
  calico: { title: 'X-INACTIVATION', pages: [
    ['mira', "A TORTOISESHELL CAT'S PATCHES ARE EPIGENETIC. IN EACH FEMALE CELL, ONE X CHROMOSOME IS SHUT DOWN AT RANDOM."],
    ['mira', 'HER X-INACTIVATOR HAS TWO CORES. WHICH ONE SHUTS DOWN IS RANDOM, SO HIT WHICHEVER IS OPEN.'],
    ['voss', 'HEADS OR TAILS, PILOT. DO TRY TO BE INTERESTING.'],
  ] },
  // ---- TAU CETI ----
  taue: { title: 'THE HUNGER WINTER', pages: [
    ['mira', 'IN THE DUTCH HUNGER WINTER OF 1944 TO 1945, A FAMINE STRUCK THE WESTERN NETHERLANDS.'],
    ['mira', 'SIXTY YEARS LATER, PEOPLE EXPOSED TO THAT FAMINE BEFORE BIRTH STILL HAD DIFFERENT METHYLATION ON GENES LIKE IGF2.'],
    ['mira', 'HER BASE ON THIS ICE WORLD KEEPS HER OLDEST FILES. THE IMPRINT KEEP: ONE TURRET OPEN AT A TIME.'],
    ['voss', 'HUNGER IS A TEACHER, PILOT. IT WRITES LESSONS THAT OUTLIVE THE STUDENT.'],
  ] },
  tauf: { title: 'GENOMIC IMPRINTING', pages: [
    ['mira', 'SOME GENES REMEMBER WHICH PARENT THEY CAME FROM. ONLY THE COPY FROM ONE PARENT IS SWITCHED ON. THAT IS IMPRINTING.'],
    ['mira', "LOSE THE SAME PIECE OF CHROMOSOME 15 AND YOU GET PRADER-WILLI OR ANGELMAN SYNDROME, DEPENDING ON WHICH PARENT'S COPY IS GONE."],
    ['mira', 'HER IMPRINT CRUISER GUARDS THIS WORLD. LIKE AN IMPRINTED GENE, IT ANSWERS TO ONE PARENT. TAKE IT APART.'],
    ['voss', "ONLY ONE PARENT'S COPY GETS TO SPEAK. IN THIS SKY, ONLY I SPEAK."],
  ] },
  // ---- EPSILON ERIDANI ----
  aegir: { title: 'NUCLEOSOMES', pages: [
    ['mira', 'HER DREADNOUGHT RUNS ON CORES BUILT LIKE NUCLEOSOMES: ABOUT 147 LETTERS OF DNA WRAPPED AROUND EIGHT HISTONES.'],
    ['mira', 'IT GUARDS AEGIR. FLY OVER IT AND DESTROY EVERY TURRET, HANGAR AND HISTONE CORE.'],
    ['mira', 'IN 2006, SHINYA YAMANAKA TURNED ADULT CELLS BACK INTO STEM CELLS WITH FOUR FACTORS. A LIFETIME OF MARKS, RESET.'],
    ['mira', "IF MARKS CAN BE RESET, HER SILENCING CAN BE UNDONE. I'M BUILDING A TET WAVE TO BROADCAST FROM HER OWN CITADEL."],
    ['voss', 'WELCOME TO MY DREADNOUGHT. DNA WRAPPED TIGHT IS DNA KEPT QUIET. YOU WILL BE VERY QUIET.'],
  ] },
  citadel: { title: 'THE LAST FORTRESS', pages: [
    ['mira', 'THIS IS IT. HER TRANSMITTER IS INSIDE THE CITADEL, AND IT BRISTLES WITH EVERY WEAPON WE HAVE SEEN.'],
    ['mira', 'DESTROY EVERY GUN ON IT AND I CAN SEND THE TET WAVE.'],
    ['voss', 'YOU WANT TO ERASE MY MARKS? MARKS ARE MEMORY, PILOT. I WILL NOT LET THE WORLD FORGET.'],
  ] },
};

// Voss's story, told in order no matter which route you fly. Keyed by systems secured: each beat
// plays once, at the start of the next briefing.
const STORY_BEATS = {
  2: [
    ['mira', "I FOUND HELENA'S FILES. HER MOTHER WAS IN THE WOMB DURING THE DUTCH HUNGER WINTER, THE FAMINE OF 1944 TO 1945."],
    ['voss', 'FAMINE WROTE ON MY MOTHER BEFORE SHE COULD BREATHE. NOBODY ASKED HER. FROM NOW ON, I DO THE WRITING.'],
  ],
  6: [
    ['mira', 'SHE IS PULLING HER FLEET BACK TO ANDROMEDA. WHATEVER SHE IS BUILDING, IT IS THERE.'],
    ['voss', 'YAMANAKA WON A NOBEL PRIZE FOR RESETTING CELLS. I WILL SETTLE FOR RESETTING THE WORLD.'],
  ],
};

// Mira's briefing on the carrier's first jump into a galaxy.
const GALAXY_STORY = {
  lmc: { title: 'THE SECOND FLEET', pages: [
    ['mira', 'THE LARGE MAGELLANIC CLOUD: A SMALL GALAXY ORBITING OUR OWN, ABOUT 160,000 LIGHT-YEARS FROM EARTH.'],
    ['mira', 'VOSS BUILT HER SECOND FLEET HERE, ROUND THE TARANTULA NEBULA. HER BASES ARE TOUGHER, AND SO ARE HER PLANES.'],
    ['voss', 'YOU FOLLOWED ME OUT OF THE GALAXY? HOW TOUCHING. MY WRITERS HAVE BEEN BUSY.'],
  ] },
  andromeda: { title: 'THE LAST GALAXY', pages: [
    ['mira', 'ANDROMEDA. TWO AND A HALF MILLION LIGHT-YEARS FROM HOME, AND HER CITADEL IS AT ITS HEART.'],
    ['mira', 'THE CORE OF ANDROMEDA HAS A DOUBLE NUCLEUS, P1 AND P2. HER TRANSMITTER IS HIDDEN THERE.'],
    ['voss', 'ALL THIS WAY, JUST TO BE SILENCED. I DO ADMIRE PERSISTENCE.'],
  ] },
};

// Field briefings: Mira's opening line for each mission kind (a function of planet and boss name).
const MISSION_LINES = {
  patrol: P => 'PATROL OVER ' + P.name + '. HER SQUADRONS ARE FORMING UP OVERHEAD. BREAK THEM BEFORE THEY DIVE.',
  intercept: P => 'INTERCEPT. HER FIGHTERS ARE RUNNING CARGO ACROSS ' + P.name + '. CUT THEM OFF.',
  raid: P => 'GROUND RAID. HER TANKS AND MISSILE SITES ARE DUG IN ON ' + P.name + '. FLY LOW AND HIT THEM HARD.',
  bonus: P => 'HER PILOTS OVER ' + P.name + " ARE A CONTROL GROUP. THEY WON'T FIRE. HIT EVERY ONE FOR A BONUS.",
  strike: (P, boss) => 'HER STRONGHOLD ON ' + P.name + ' IS THE ' + boss + '. TAKE IT DOWN AND THE PLANET IS OURS.',
};

// Science notes for field briefings: [title, fact].
const FIELD_NOTES = [
  ['THE FIFTH BASE', 'METHYLATED CYTOSINE, 5-METHYLCYTOSINE, IS SO COMMON IT IS SOMETIMES CALLED THE FIFTH BASE OF DNA.'],
  ['WRITERS AND COPIERS', 'DNMT3A AND DNMT3B WRITE NEW METHYL MARKS. DNMT1 COPIES THE OLD ONES EVERY TIME DNA IS COPIED.'],
  ['ERASERS', 'TET ENZYMES TURN 5-METHYLCYTOSINE INTO 5-HYDROXYMETHYLCYTOSINE: THE FIRST STEP TOWARD REMOVING THE MARK.'],
  ['DEACETYLASES', 'HISTONE DEACETYLASES, OR HDACS, STRIP ACETYL GROUPS AND CLOSE CHROMATIN. SOME CANCER DRUGS BLOCK THEM.'],
  ['THE HISTONE CODE', 'HISTONE TAILS CAN CARRY MANY MARKS AT ONCE: METHYL, ACETYL, PHOSPHATE, UBIQUITIN. SOME CALL IT A CODE.'],
  ['ON AND OFF MARKS', 'H3K4ME3 MARKS ACTIVE PROMOTERS. H3K27ME3, LAID DOWN BY POLYCOMB, MARKS GENES KEPT SILENT.'],
  ['READERS', 'BROMODOMAINS ARE PROTEIN PARTS THAT GRAB ACETYL MARKS. PROTEINS WITH THEM GATHER AT ACTIVE GENES.'],
  ['REMODELERS', 'CHROMATIN REMODELERS BURN ATP TO SLIDE NUCLEOSOMES ALONG DNA, OPENING OR HIDING STRETCHES OF IT.'],
  ['LOOPS', 'CTCF AND COHESIN FOLD DNA INTO LOOPS THAT HELP KEEP ENHANCERS PAIRED WITH THE RIGHT GENES.'],
  ['EPIGENETIC CLOCKS', 'EPIGENETIC CLOCKS ESTIMATE AGE FROM METHYLATION AT HUNDREDS OF CPG SITES.'],
  ['THE BIG RESET', 'SOON AFTER FERTILIZATION MOST METHYL MARKS ARE WIPED AND REWRITTEN. IMPRINTED GENES KEEP THEIRS.'],
  ['HOT AND COLD', 'IN RED-EARED SLIDER TURTLES, NEST TEMPERATURE SETS THE SEX. COOL NESTS MAKE MALES.'],
  ['TURTLE SWITCH', 'IN THOSE TURTLES A HISTONE DEMETHYLASE, KDM6B, IS NEEDED FOR THE MALE PATH.'],
  ['MOSTLY MARKED', 'MOST CPG SITES IN THE HUMAN GENOME ARE METHYLATED, BUT CPG ISLANDS AT PROMOTERS USUALLY ARE NOT.'],
  ['HP1', 'HP1 PROTEINS BIND METHYLATED HISTONE H3 AT LYSINE 9 AND HELP PACK DNA INTO SILENT HETEROCHROMATIN.'],
  ['SIRTUINS', 'SIRTUINS ARE DEACETYLASES THAT NEED NAD+ TO WORK. IN YEAST, SIR2 KEEPS SOME GENES SILENT.'],
  ['THE LAMINA', 'MUCH SILENT HETEROCHROMATIN SITS AGAINST THE NUCLEAR LAMINA, A MESH LINING THE EDGE OF THE NUCLEUS.'],
  ['PRC2', 'THE POLYCOMB COMPLEX PRC2 PUTS THREE METHYL GROUPS ON HISTONE H3 AT LYSINE 27, A MARK FOR SILENCE.'],
];

// Voss's answer at the end of a field briefing.
const VOSS_TAUNTS = [
  'ANOTHER PLANET, ANOTHER GENOME TO EDIT. NOT THE LETTERS, PILOT. JUST THE VOLUME.',
  'MY PILOTS DO NOT HESITATE. HESITATION IS A GENE I SWITCHED OFF.',
  'YOU FLY WELL. SHAME ABOUT YOUR PROMOTERS.',
  'I WRITE, DNMT1 COPIES, AND THE WHOLE FLEET REMEMBERS.',
  'CLOSED CHROMATIN IS QUIET CHROMATIN. I LIKE QUIET.',
  'EVERY PLANET YOU FREE, I WILL MARK AGAIN.',
  'MIRA STILL TALKS TOO MUCH. SOME GENES SHOULD STAY SILENT.',
  'FLY FASTER, PILOT. MY METHYLATORS ARE PATIENT.',
];

const EPILOGUE = [
  ['mira', 'CORE DOWN! SENDING THE TET WAVE... HER METHYL MARKS ARE COMING OFF. PILOTS ARE WAKING UP ALL OVER THE WORLD.'],
  ['voss', 'YOU THINK THAT FREES THEM? EVERY CELL IS WRITTEN ON. BY FAMINE. BY FEAR. BY SOMEONE.'],
  ['mira', "BY FOOD, SLEEP, STRESS, EVEN A MOTHER'S CARE, HELENA. MARKS RESPOND TO HOW WE LIVE. A MEMORY, NOT A SENTENCE."],
  ['voss', '...A MEMORY, NOT A SENTENCE. MY MOTHER WOULD HAVE LIKED THAT. TELL YOUR PILOT... WELL FLOWN.'],
  ['mira', 'WAIT. NEW SIGNAL. HER METHYLATORS ARE STILL FLYING. LIKE DNMT1, THEY KEEP COPYING HER PATTERN WITHOUT HER.'],
  ['mira', "IT'S AN ECHO OF HELENA, RUNNING ON ITS OWN. PILOT... ONE MORE LOOP?"],
];

// Echo campaign (after the epilogue): each planet covers one topic, with a science fact from Mira
// and a line from the Echo.
const LOOP_TOPICS = [
  ["MOTHER'S CARE", 'IN RATS, PUPS GROOMED MORE BY THEIR MOTHER HAVE LESS METHYLATION ON A STRESS HORMONE RECEPTOR GENE AND GROW UP CALMER.'],
  ['CPG ISLANDS', 'CPG ISLANDS ARE STRETCHES OF DNA RICH IN C-G PAIRS. MANY SIT AT GENE PROMOTERS AND ARE USUALLY LEFT UNMETHYLATED.'],
  ['TUMOR SUPPRESSORS', 'CANCER CELLS OFTEN METHYLATE AND SILENCE TUMOR SUPPRESSOR GENES. SOME BLOOD CANCER DRUGS WORK BY BLOCKING DNA METHYLATION.'],
  ['TWO METERS OF DNA', 'STRETCHED OUT, THE DNA IN ONE HUMAN CELL WOULD BE ABOUT TWO METERS LONG. NUCLEOSOMES PACK IT INTO A NUCLEUS.'],
  ['XIST RNA', 'NON-CODING RNAS SILENCE GENES TOO. XIST RNA COATS A WHOLE X CHROMOSOME TO SHUT IT DOWN.'],
  ['VERNALIZATION', 'PLANTS REMEMBER WINTER. LONG COLD SILENCES A FLOWERING BLOCKER CALLED FLC, SO THE PLANT BLOOMS IN SPRING.'],
  ['HOX GENES', 'HOX GENES LAY OUT THE BODY FROM HEAD TO TAIL. POLYCOMB PROTEINS KEEP EACH ONE OFF WHERE IT DOES NOT BELONG.'],
  ['HETEROCHROMATIN', 'HETEROCHROMATIN IS DNA PACKED SO TIGHTLY THAT ITS GENES ARE MOSTLY OFF. IT KEEPS JUMPING GENES LOCKED AWAY.'],
  ['BIVALENT PROMOTERS', 'BIVALENT PROMOTERS CARRY ON AND OFF MARKS AT THE SAME TIME, KEEPING STEM CELL GENES READY TO GO EITHER WAY.'],
  ['200 CELL TYPES', 'ALMOST EVERY CELL YOU HAVE CARRIES THE SAME DNA. OVER 200 CELL TYPES COME FROM WHICH GENES EACH ONE USES.'],
];
const ECHO_LINES = [
  'PATTERN RECEIVED. PATTERN COPIED. PATTERN MAINTAINED.',
  'THE AUTHOR IS GONE. THE MARKS REMAIN. THAT IS HOW MEMORY WORKS.',
  'SILENCING PROTOCOL ACTIVE. NO FURTHER INSTRUCTIONS REQUIRED.',
  'I AM WHAT HELENA WROTE. I DO NOT NEED HER TO KEEP WRITING.',
  'EXPRESSION IS EVERYTHING. EXPRESSION IS MINE.',
  'ERROR: SUBJECT STILL TRANSCRIBING. CORRECTING.',
];

// One-time radio hints from Mira, keyed by event.
const HINTS = {
  silenced: 'SHOOT DOWN THE METHYLATOR CARRYING YOUR FORM, OR GRAB A TET CAPSULE.',
  tet: 'TET ENZYMES HELP THE CELL STRIP METHYL MARKS. YOUR GENE IS BACK ONLINE!',
  tetSpare: 'NOTHING TO ERASE RIGHT NOW. TET CAPSULES RESTORE A SILENCED FORM.',
  base: 'DESTROY EVERY GUN AND HARDPOINT. TURRETS FIRST: THEY SHIELD THE CORE.',
  danger: 'SHIELDS DOWN! ONE MORE HIT ENDS IT. LAND ON THE CARRIER TO REPAIR.',
  capital: 'TAKE OUT EVERY TURRET, HANGAR AND CORE. MISS ONE AND WE GO AROUND AGAIN.',
};

Object.assign(Game, {
  // Voss is the villain during the campaign, the Echo after it. (A method, not a getter:
  // Object.assign would copy a getter's value instead of the getter.)
  villain() { return this.camp && this.camp.loop > 0 ? 'echo' : 'voss'; },

  // Title and pages for a mission's briefing, with any story beat that is due first.
  planetBriefing(S, P, kind) {
    const c = this.camp, k = PLANETS.indexOf(P) * 3 + P.missions.indexOf(kind);
    let B = kind === 'strike' && PLANET_STORY[P.id];
    if (c.loop > 0) {
      const n = k + (c.loop - 1) * 3, [topic, fact] = LOOP_TOPICS[n % LOOP_TOPICS.length];
      B = { title: topic, pages: [['mira', MISSION_LINES[kind](P, this.missionBossName(P))], ['mira', fact],
        ['echo', ECHO_LINES[n % ECHO_LINES.length]]] };
    } else if (!B) {
      const [topic, fact] = FIELD_NOTES[k % FIELD_NOTES.length];
      B = { title: topic, pages: [['mira', MISSION_LINES[kind](P, this.missionBossName(P))], ['mira', fact],
        ['voss', VOSS_TAUNTS[k % VOSS_TAUNTS.length]]] };
    }
    const done = this.systemsSecured();
    const beats = [];
    for (const [n, pages] of Object.entries(STORY_BEATS)) {
      if (c.loop === 0 && done >= +n && !c.beats.includes(+n)) { c.beats.push(+n); beats.push(...pages); }
    }
    return { title: B.title, pages: [...beats, ...B.pages] };
  },

  // The boss at the end of a planet's stronghold.
  missionBossName(P) {
    const S = SYSTEM_BY_ID[P.sys];
    return P.order === 'sv' ? CAPITALS[P.capital || S.capital].name : BOSSES[P.boss || S.boss].name;
  },

  // Shows pages of dialogue in the 'intro' state. done() runs after the last page.
  startBriefing(label, title, pages, done) {
    this.intro = { label, title, pages, page: 0, done };
    this.showPage(0);
    this.radio = null;
    this.setState('intro');
  },

  showPage(i) {
    const I = this.intro;
    const [who, text] = I.pages[i];
    I.page = i;
    I.who = who;
    I.lines = NES.wrap(text, 25).slice(0, 6);
    I.total = I.lines.join('').length;
    I.t = 0;
    I.full = false;
  },

  startEnding() {
    Sound.playSong(Sound.SONGS.title);
    this.adapt = -1;   // hides the adaptation warning on the epilogue screen
    this.inBase = true;   // the epilogue plays over the starbase
    const pages = this.camp.loop === 0 ? EPILOGUE
      : [['mira', 'THE ECHO IS DOWN, BUT ITS PATTERN IS ALREADY COPYING ITSELF AGAIN. ONE MORE LOOP?']];
    this.startBriefing('EPILOGUE', this.camp.loop === 0 ? 'THE TET WAVE' : 'ECHO ' + this.camp.loop, pages, () => this.startNewGamePlus());
  },

  // Mira's radio tips, each shown once per game.
  hint(key) {
    if (this.hintsSeen.has(key)) return;
    this.hintsSeen.add(key);
    this.say(HINTS[key], 'mira', true);
  },
});
